[en]
description="$b1MT its an utility cryptocurrency that can be used to pay for advertising and gamble with it in slots, dice, and roulette"
contract="contract"

[es]
description="$b1MT es una criptomoneda de utilidad que puede ser usado para pagar publicidad, como moneda de cambio en casinos online y redes sociales"
contract="contrato"
