[en]
home="Home"
tokenomics="Tokenomics"
use_cases="Use Cases"
buy="Buy"
stake="Stake"
road_map="Road map"
community="Community"
description="$b1MT its an utility cryptocurrency that can be used to pay for advertising and gamble with it in slots, dice, and roulette"
community_project="This proyect is developed and drived by the community. Without ownership but with governance"
contract="contract"
launch="b1MT launch"
governance="Governance"
kennel_token_pool="Pool in Kennel Token"
web="Web for b1MT"
swap_web="Integrate swap for web"
partner_app="Partner app"
automata_token="1MT in Automata Network"
governance_web="Integrate governance in web"
cross_swap="Swap from Ata Network to BSC or ETH"
partner_with_1mt="Partner with 1mt"
partner_with_1mt_description="By holding the 2500 $b1MT you will get:<ul><li>1 week of free services ( 1 CMS reddit post 1 post on twitter 1 on discord each 2 days)</li><li>Post on partners channel in 1MT discord once a day, you can use @everyone to ping the community</li></ul>"
vegas_casino_description="Play a different casino game in this discord server. You can buy casino coins with b1MT or 1MT. Play with responsability"
moneytime="Moneytime is an unique project that offer multiple options for $b1MT to get profits: <ul><li>b1MT/BNB earn $Time farming pool!</li><li>Stake $Money earn $b1MT</li><li>Stake $1MT earn $Time</li></ul>"
the_kennel_token_description="The Token Kennel is the best way to stake your $b1MT for long term and receive nice APY between 80%-300%, you only need to hold 250 $KENNEL in your wallet for it. The deposit and withdraw have a fee of 10% and this is distributed for the liquidity providers. Every two weeks there is a vote where the winner pool get a repayment increasing again the APY, $b1MT has won all the repayment until now. See more in <a href='https://thetokenkennel.com/'>The Kennel Token</a>."
slogan="Limited supply for big goals"
slogan_description="The supply of $b1MT is limited, so it is the best token candidate for storing value, and it also has multiple use cases"

[es]
home="Inicio"
tokenomics="Tokenomics"
use_cases="Casos Prácticos"
buy="Comprar"
stake="Depositar"
road_map="Hoja de ruta"
community="Comunidad"
description="$b1MT es una criptomoneda de utilidad que puede ser usado para pagar publicidad, como moneda de cambio en casinos online y redes sociales"
community_project="Este proyecto es desarrollado y dirigido por la comunidad. Sin propietario pero gobernado por sus poseedores"
contract="contrato"
launch="Lanzamiento de b1MT"
governance="Gobernabilidad"
kennel_token_pool="Deposito en Kennel Token"
web="Web para b1MT"
swap_web="Integrar intercambiador en la web"
partner_app="App para socios"
automata_token="1MT en Automata Network"
cross_swap="Intercambiar desde Ata Network a BSC o ETH"
governance_web="Integrar gobernabilidad en la web"
partner_with_1mt="Asociarse con 1mt"
partner_with_1mt_description="Mantenindo 2500 $b1MT en la cartera obtendras:<ul><li>Una semana gratuita de publicidad ( un anuncio en reddit, twitter y en discord cada dos dias )</li><li>Anunciarse en el canal partners de discord de 1MT una vez al dia, puede usar @everyone para hacer ping a la communidad</li></ul>"
vegas_casino_description="Juega a diferentes juego de casinos en este servidor de Discord. Puedes comprar monedas de casino con b1MT o 1MT. Juega siempre con responsabilidad"
moneytime="Moneytime es un proyecto único que ofrece múltiples opciones para obtener beneficios con $b1MT: <ul><li> b1MT/BNB gana $Time con deposito de farmeo</li><li>Deposita $Money y gana $b1MT</li><li>Deposita $1MT y gana $Time</li></ul>"
the_kennel_token_description="The Token Kennel es la mejor manera de depositar sus $b1MT y recibir un atractivo interés entre 80%-300%, solo necesita disponer de 250 $KENNEL en su cartera para eso. El despósito y retiro tiene una comisión de 10% que se distribuye a todos los proveedores de liquidez. Cada dos semanas hay una votación y el deposito ganador recibe un repago incrementando el interés. $b1MT ha ganado todos los repagos hasta ahora. Ver más en <a href='https://thetokenkennel.com/' target='_blank'>The Kennel Token</a>."
slogan="Limitada cantidad para grandes metas"
slogan_description="Debido a que hay una cantidad limitada de $b1MT es el candidato idoneo para utilizarlo como deposito de valor, además dispone de muchos casos prácticos"
