[en]
home="Home"
tokenomics="Tokenomics"
buy="Buy"
stake="Stake"
road_map="Road map"
community="Community"
description="$b1MT its an utility cryptocurrency that can be used to pay for advertising and gamble with it in slots, dice, and roulette"
contract="contract"
launch="b1MT launch"
governance="Governance"
kennel_token_pool="Pool in Kennel Token"
web="Web for b1MT"
swap_web="Integrate swap for web"
automata_token="1MT in Automata Network"
governance_web="Integrate governance in web"
cross_swap="Swap from Ata Network to BSC or ETH"

[es]
home="Inicio"
tokenomics="Tokenomics"
buy="Comprar"
stake="Depositar"
road_map="Hoja de ruta"
community="Comunidad"
description="$b1MT es una criptomoneda de utilidad que puede ser usado para pagar publicidad, como moneda de cambio en casinos online y redes sociales"
contract="contrato"
launch="Lanzamiento de b1MT"
governance="Gobernabilidad"
kennel_token_pool="Deposito en Kennel Token"
web="Web para b1MT"
swap_web="Integrar intercambiador en la web"
automata_token="1MT en Automata Network"
cross_swap="Intercambiar desde Ata Network a BSC o ETH"
governance_web="Integrar gobernabilidad en la web"
