[en]
home="Home"
tokenomics="Tokenomics"
use_cases="Use Cases"
buy="Buy"
stake="Stake"
road_map="Road map"
community="Community"
description="$b1MT its an utility cryptocurrency that can be used to pay for advertising and gamble with it in slots, dice, and roulette"
contract="contract"
launch="b1MT launch"
governance="Governance"
kennel_token_pool="Pool in Kennel Token"
web="Web for b1MT"
swap_web="Integrate swap for web"
automata_token="1MT in Automata Network"
governance_web="Integrate governance in web"
cross_swap="Swap from Ata Network to BSC or ETH"
partner_with_1mt="Partner with 1mt"
partner_with_1mt_description="By holding the 2500 $b1MT you will get:\n * 1 week of free services ( 1 CMS reddit post 1 post on twitter 1 on discord each 2 days)\n* Post on partners channel in 1MT discord once a day, you can use @everyone to ping the community"
vegas_casino_description="Play a different casino game in this discord server. You can buy casino coins with b1MT or 1MT. Play with responsability"

[es]
home="Inicio"
tokenomics="Tokenomics"
use_cases="Casos Prácticos"
buy="Comprar"
stake="Depositar"
road_map="Hoja de ruta"
community="Comunidad"
description="$b1MT es una criptomoneda de utilidad que puede ser usado para pagar publicidad, como moneda de cambio en casinos online y redes sociales"
contract="contrato"
launch="Lanzamiento de b1MT"
governance="Gobernabilidad"
kennel_token_pool="Deposito en Kennel Token"
web="Web para b1MT"
swap_web="Integrar intercambiador en la web"
automata_token="1MT en Automata Network"
cross_swap="Intercambiar desde Ata Network a BSC o ETH"
governance_web="Integrar gobernabilidad en la web"
partner_with_1mt="Asociarse con 1mt"
partner_with_1mt_description="Mantenindo 2500 $b1MT en la cartera obtendras:\n * Una semana gratuita de publicidad ( un anuncio en reddit, twitter y en discord cada dos dias )\n* Anunciar en canal partners en el discord de 1MT una vez al dia, puede usar @everyone para hacer ping a la communidad"
vegas_casino_description="Juega a diferentes juego de casinos en este servidor de Discord. Puedes comprar monedas de casino con b1MT o 1MT. Juega siempre con responsabilidad"
